# Generated by Django 4.2.21 on 2025-05-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movieprovider_delete_ottavailability_movie_providers'),
        ('accounts', '0002_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_movie',
            field=models.ManyToManyField(related_name='liked_user', to='movies.movie'),
        ),
    ]
