# Generated by Django 4.2.21 on 2025-05-26 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
