# Generated by Django 4.2.21 on 2025-05-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_like_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/default.png', upload_to='profile/'),
        ),
    ]
