# Generated by Django 4.2.21 on 2025-05-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_birth_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_bio',
            field=models.CharField(default='', max_length=30),
        ),
    ]
