# Generated by Django 4.2.21 on 2025-05-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_bio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
