# Generated by Django 4.2.21 on 2025-05-22 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tmdb_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('adult', models.BooleanField()),
                ('budget', models.PositiveIntegerField()),
                ('tmdb_id', models.PositiveIntegerField()),
                ('origin_country', models.CharField(max_length=50)),
                ('runtime', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('tagline', models.CharField(max_length=100)),
                ('vote_average', models.FloatField()),
                ('poster_path', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='OTTAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ManyToManyField(through='movies.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
