# Generated by Django 4.2.21 on 2025-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
