# Generated by Django 4.2.21 on 2025-05-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tmdb_id', models.PositiveIntegerField()),
                ('logo_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='OTTAvailability',
        ),
        migrations.AddField(
            model_name='movie',
            name='providers',
            field=models.ManyToManyField(blank=True, to='movies.movieprovider'),
        ),
    ]
